server:
  port: 9093

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000


spring:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
    main:
      allow:
      bean-definition-overriding: true

javainuse:
  rabbitmq:
    exchange: atlantico.exchange
    queue: atlantico.queue
    routingkey: atlantico.routingkey
    


